FROM {{base_image}}
ADD {{rootfs}} /

EXPOSE 9631 {{exposes}}
RUN SET HAB_FEAT_OFFLINE_INSTALL=ON && \
    {{~ #if environment}}
    {{~ #each environment}}
        SET {{@key}}={{{this}}}&& \
    {{~ /each}}
    {{~ /if}}
    {{bio_path}} pkg install {{installed_primary_svc_ident}}
ENTRYPOINT ["{{bio_path}}", "sup", "run", "{{primary_svc_ident}}"]
