[package]
name = "biome-rst-reader"
version = "0.0.0"
authors = ["The Biome Maintainers <humans@biome.sh>"]
edition = "2018"
workspace = "../../"

[[bin]]
name = "rst-reader"
path = "src/main.rs"
doc = false

[dependencies]
clap = { git = "https://github.com/habitat-sh/clap.git", branch = "v2-master", features = [ "suggestions", "color", "unstable" ] }
env_logger = "*"
biome_butterfly = { path = "../butterfly", default-features = false }
log = "^0.4.11"
